language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
script:
  - "npm run coverage"
  - "npm run test-lib"
  - "npm run test-browser"
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
