language: node_js
env:
  - TARGET=test-lib
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
matrix:
  include:
    - name: Lint
      node_js: '8'
      env:
        - TARGET=lint
    - name: Coverage
      node_js: '8'
      env:
        - TARGET=coverage
    - name: Browser
      node_js: '8'
      env:
        - TARGET=test-browser
script: npm run $TARGET
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
